settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: newapi
    name: New API
    url: 'https://new.kougami.cn/'
    method: GET
    expectStatus: 200

  - id: serv00-alist
    name: AList(Serv00)
    url: 'https://alist.kougami.cn/'
    method: GET
    expectStatus: 200

  - id: tool
    name: 在线工具箱(Serv00)
    url: 'https://tool.kougami.cn/'
    method: GET
    expectStatus: 200

  - id: rsshub
    name: RSSHub(US)
    url: 'https://rss.kougami.us.kg/'
    method: GET
    expectStatus: 200

  - id: imgbed
    name: 图床(CloudFlare Telegram)
    url: 'https://rss.kougami.us.kg/'
    method: GET
    expectStatus: 200

  - id: dockerhub-mirrors
    name: DockerHub镜像源(CloudFlare)
    url: 'https://docker.kougami.us.kg/'
    method: GET
    expectStatus: 200

  - id: napcat
    name: NapCat推送机器人(Pi)
    url: 'https://bot.kougami.cn/'
    method: GET
    expectStatus: 200
